# Generated by Django 3.0.9 on 2021-10-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211024_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='category',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
