# Generated by Django 3.0.9 on 2021-10-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
